### PR TITLE
Landing page html and css

### PR DESCRIPTION
**Pull request by woubuc**

### CODE REVIEW

**Comment by Chocksy** [comment]
@woubuc nice work :dancer: :+1:

**Comment by Chocksy** [comment]
@woubuc can you add here the converted `less -> sass` files? Leave the less ones too. :D Once we have that i'll merge it.

**Comment by woubuc** [comment]
@Chocksy I added the converted SASS files and fixed a problem with the background image scaling. Everything should be okay now.

**Comment by Chocksy** [comment]
cool i'll merge it. Thanks

**Pull request merged**
